export const nigeriaCities = {
  Abia: ['Aba', 'Umuahia', 'Ohafia', 'Arochukwu', 'Umunneochi'],
  Adamawa: ['Yola', 'Mubi', 'Ganye', 'Hong', 'Michika'],
  AkwaIbom: ['Uyo', 'Eket', 'Ikot Ekpene', 'Oron', 'Abak'],
  Anambra: ['Awka', 'Onitsha', 'Nnewi', 'Ekwulobia', 'Ihiala'],
  Bauchi: ['Bauchi', 'Azare', 'Misau', 'Jama’are', 'Tafawa Balewa'],
  Bayelsa: ['Yenagoa', 'Amassoma', 'Ogbia', 'Brass', 'Sagbama'],
  Benue: ['Makurdi', 'Gboko', 'Otukpo', 'Katsina-Ala', 'Vandeikya'],
  Borno: ['Maiduguri', 'Biu', 'Dikwa', 'Gwoza', 'Ngala'],
  CrossRiver: ['Calabar', 'Ogoja', 'Ikom', 'Obudu', 'Ugep'],
  Delta: ['Asaba', 'Warri', 'Sapele', 'Ughelli', 'Agbor'],
  Ebonyi: ['Abakaliki', 'Afikpo', 'Onueke', 'Ishieke', 'Ezzamgbo'],
  Edo: ['Benin City', 'Ekpoma', 'Auchi', 'Uromi', 'Okhuesan'],
  Ekiti: ['Ado-Ekiti', 'Ikere-Ekiti', 'Ode-Ekiti', 'Ikole', 'Ise-Ekiti'],
  Enugu: ['Enugu', 'Nsukka', 'Agbani', 'Awgu', 'Udi'],
  FCT: ['Abuja', 'Gwagwalada', 'Kuje', 'Kwali', 'Abaji'],
  Gombe: ['Gombe', 'Kaltungo', 'Billiri', 'Dukku', 'Bajoga'],
  Imo: ['Owerri', 'Orlu', 'Okigwe', 'Mbaise', 'Oguta'],
  Jigawa: ['Dutse', 'Hadejia', 'Kazaure', 'Gumel', 'Birnin Kudu'],
  Kaduna: ['Kaduna', 'Zaria', 'Kafanchan', 'Soba', 'Ikara'],
  Kano: ['Kano', 'Dala', 'Dawakin Tofa', 'Wudil', 'Gaya'],
  Katsina: ['Katsina', 'Daura', 'Funtua', 'Malumfashi', 'Kankia'],
  Kebbi: ['Birnin Kebbi', 'Argungu', 'Yauri', 'Zuru', 'Koko'],
  Kogi: ['Lokoja', 'Okene', 'Kabba', 'Idah', 'Ankpa'],
  Kwara: ['Ilorin', 'Offa', 'Omu-Aran', 'Kaiama', 'Patigi'],
  Lagos: ['Lagos', 'Ikeja', 'Lekki', 'Victoria Island', 'Surulere', 'Badagry', 'Epe', 'Ikorodu'],
  Nasarawa: ['Lafia', 'Keffi', 'Akwanga', 'Nasarawa', 'Doma'],
  Niger: ['Minna', 'Suleja', 'Bida', 'Kontagora', 'Lapai'],
  Ogun: ['Abeokuta', 'Ijebu-Ode', 'Sagamu', 'Ota', 'Ilaro'],
  Ondo: ['Akure', 'Ondo', 'Owo', 'Ikare', 'Idanre'],
  Osun: ['Osogbo', 'Ife', 'Ilesa', 'Ede', 'Ikirun'],
  Oyo: ['Ibadan', 'Ogbomoso', 'Oyo', 'Saki', 'Iseyin'],
  Plateau: ['Jos', 'Bukuru', 'Barkin Ladi', 'Pankshin', 'Shendam'],
  Rivers: ['Port Harcourt', 'Bonny', 'Degema', 'Okrika', 'Ahoada'],
  Sokoto: ['Sokoto', 'Tambuwal', 'Binji', 'Gwadabawa', 'Illela'],
  Taraba: ['Jalingo', 'Wukari', 'Sardauna', 'Takum', 'Bali'],
  Yobe: ['Damaturu', 'Nguru', 'Potiskum', 'Gashua', 'Geidam'],
  Zamfara: ['Gusau', 'Kaura Namoda', 'Talata Mafara', 'Anka', 'Maru'],
};
